// <auto-generated />
namespace VideoRental.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seed_Gender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seed_Gender));
        
        string IMigrationMetadata.Id
        {
            get { return "201710150603493_Seed_Gender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
